### ISSUE TITLE
feat: allow to automate authentication

### ISSUE THREAD

**Issue by getlarge** [s1seven/node-red-monorepo#6]
# Description

**Is this a BUG REPORT or FEATURE REQUEST ?** FEATURE REQUEST

**What you expected to happen :**

With the new authentication mechanism for M2M access to be soon released, we should provide some node(s) that gives read/write access to application entities and create/regenerate an access token.
Also we should update our demo workflows to show how to configure/use those nodes.

**Comment by eamon0989** [comment]
A simple solution is to update our current config node (or create a new one) that allow the storage of `ClientId` and `ClientSecret`. Then, a new node can be created that simply calls the POST `/api/tokens` endpoint and regenerates the client secret. This process can be automated via an inject node, which can be set to run once every x hours.

**Comment by getlarge** [comment]
> A simple solution is to update our current config node (or create a new one) that allow the storage of `ClientId` and `ClientSecret`. Then, a new node can be created that simply calls the POST `/api/tokens` endpoint and regenerates the client secret. This process can be automated via an inject node, which can be set to run once every x hours.

Let's combine that change with #3 which also relates to the config node.
